export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const LIST_TODO = 'LIST_TODO';
export const DETAIL_TODO = 'DETAIL_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const SAGA_FETCH_REQUESTED = 'SAGA_FETCH_REQUESTED';
export const SAGA_FETCH_SUCCEEDED = 'SAGA_FETCH_SUCCEEDED';
